/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router';

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>;
    '/_admin': RouteRecordInfo<
      '/_admin',
      '/_admin',
      Record<never, never>,
      Record<never, never>
    >;
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> }
    >;
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>
    >;
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>
    >;
    '/admin/dashboard': RouteRecordInfo<
      '/admin/dashboard',
      '/admin/dashboard',
      Record<never, never>,
      Record<never, never>
    >;
    '/docs/': RouteRecordInfo<
      '/docs/',
      '/docs',
      Record<never, never>,
      Record<never, never>
    >;
    'home-page': RouteRecordInfo<
      'home-page',
      '/home',
      Record<never, never>,
      Record<never, never>
    >;
    '/mypage': RouteRecordInfo<
      '/mypage',
      '/mypage',
      Record<never, never>,
      Record<never, never>,
      '/mypage/bookmark' | '/mypage/password' | '/mypage/profile'
    >;
    '/mypage/bookmark': RouteRecordInfo<
      '/mypage/bookmark',
      '/mypage/bookmark',
      Record<never, never>,
      Record<never, never>
    >;
    '/mypage/password': RouteRecordInfo<
      '/mypage/password',
      '/mypage/password',
      Record<never, never>,
      Record<never, never>
    >;
    '/mypage/profile': RouteRecordInfo<
      '/mypage/profile',
      '/mypage/profile',
      Record<never, never>,
      Record<never, never>
    >;
    '/posts/[id]/': RouteRecordInfo<
      '/posts/[id]/',
      '/posts/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> }
    >;
    '/posts/[id]/edit': RouteRecordInfo<
      '/posts/[id]/edit',
      '/posts/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> }
    >;
    '/search/': RouteRecordInfo<
      '/search/',
      '/search',
      Record<never, never>,
      Record<never, never>
    >;
    '/vueuse/': RouteRecordInfo<
      '/vueuse/',
      '/vueuse',
      Record<never, never>,
      Record<never, never>
    >;
  }
}
